#!/bin/sh
# Builds LuaDist on Unix-like systems (including Cygwin and OSX).
set -e  # exit on failure

RELEASE=`uname`
if [ $RELEASE = "" ]; then
RELEASE="luadist"
fi
echo "Bootstraping LuaDist (_bootstrap/$RELEASE)"
echo "NOTE: Add -DCMAKE_BUILD_TYPE=Release when building release version."

mkdir -p "_bootstrap/$RELEASE"
cd "_bootstrap/$RELEASE"
cmake ../.. -G "Unix Makefiles" $*
cmake --build . --target install -- -j6
