#!/bin/sh
# Builds LuaDist on Unix-like systems (including Cygwin and OSX).
set -e  # exit on failure

RELEASE=`uname`
if [ $RELEASE = "" ]; then
RELEASE="luadist"
fi
echo "Bootstraping LuaDist (_bootstrap/$RELEASE)"

mkdir -p "_bootstrap/$RELEASE"
cd "_bootstrap/$RELEASE"
cmake ../.. -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release $*
cmake --build . --target install --clean-first -- -j6
